[package]
name = "gui"
edition = "2021"
version = "0.1.0"

[dependencies]
eyre = "0.6.8"
iced = { version = "0.4.2", features = ["pure", "tokio"] }
tokio = { version = "1.19.2", features = ["net", "io-util", "sync"] }
